#!/bin/sh

nix-env --version

if command -v nixos-version >/dev/null 2>&1; then
    nixos-version
else
    nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion | sed 's/^"\(.*\)"$/\1/'
fi

./nix-uname


# TODO: add in nix options enabled
#       how to parse?
